import = [
    "~/.config/alacritty/catppuccin-macchiato.toml"]

[shell]
program = "/usr/bin/zsh"

[font]
size = 12.0
normal = { family = "FiraCode Nerd Font", style = "bold" }

[env]
term = "xterm-256color"
